-- Creating Tables

CREATE TABLE users( id INT NOT NULL AUTO_INCREMENT,
username VARCHAR(255) NOT NULL,
password VARCHAR(255) NOT NULL,
PRIMARY KEY(id));


CREATE TABLE artists(id INT AUTO_INCREMENT NOT NULL,
name VARCHAR(255) NOT NULL,
PRIMARY KEY(id));


CREATE TABLE albums( id INT AUTO_INCREMENT NOT NULL, 
	name VARCHAR(255) NOT NULL,
	 year YEAR(4), artist_id INT, 
	 PRIMARY KEY(id),
	 FOREIGN KEY(artist_id)
	 REFERENCES artists(id)
	 ON UPDATE CASCADE
	 ON DELETE CASCADE);


CREATE TABLE songs( id INT AUTO_INCREMENT NOT NULL,
title VARCHAR(255) NOT NULL,
length INT,
genre VARCHAR(255),
album_id INT,
PRIMARY KEY(id),
FOREIGN KEY(album_id)
REFERENCES albums(id)
ON UPDATE CASCADE
ON DELETE SET NULL);



CREATE TABLE playlists( id INT AUTO_INCREMENT NOT NULL,
date_created TIMESTAMP
DEFAULT CURRENT_TIMESTAMP,
user_id INT,
PRIMARY KEY(id),
FOREIGN KEY(user_id)
REFERENCES users(id)
ON UPDATE CASCADE
ON DELETE SET NULL);


CREATE TABLE playlist_song( id INT AUTO_INCREMENT NOT NULL,
song_id INT,
playlist_id INT,
PRIMARY KEY(id),
FOREIGN KEY(song_id)
REFERENCES songs(id)
ON UPDATE CASCADE
ON DELETE SET NULL,
FOREIGN KEY(playlist_id)
REFERENCES playlists(id)
ON UPDATE CASCADE
ON DELETE SET NULL);


